import {
  MdDashboard,
  MdSupervisedUserCircle,
  MdAnalytics,
  MdOutlineSettings,
  MdHelpCenter,
  MdLibraryBooks,
  MdStorage,
  MdOutlineContentPaste,
} from "react-icons/md";

export const menuAdmin = [
  {
    title: "Pages",
    list: [
      {
        title: "Dashboard",
        path: "/cpa",
        icon: <MdDashboard />,
      },
      {
        title: "Usuarios",
        path: "/cpa/users",
        icon: <MdSupervisedUserCircle />,
      },
      {
        title: "Gallery",
        path: "/cpa/gallery",
        icon: <MdDashboard />,
      },
      {
        title: "Publicaciones",
        path: "/cpa/post",
        icon: <MdLibraryBooks />,
      },
      {
        title: "Reportes",
        path: "/cpa/logs",
        icon: <MdAnalytics />,
      },
      {
        title: "Backup",
        path: "/cpa/backup",
        icon: <MdStorage />,
      },
    ],
  },
  {
    title: "Más",
    list: [
      {
        title: "Configuración",
        path: "",
        icon: <MdOutlineSettings />,
      },
      {
        title: "Ayuda",
        path: "",
        icon: <MdHelpCenter />,
      },
    ],
  },
];

export const menuAcademic = [
  {
    title: "Pages",
    list: [
      {
        title: "Dashboard",
        path: "/academic",
        icon: <MdDashboard />,
      },
      {
        title: "Kardex",
        path: "/academic/students",
        icon: <MdSupervisedUserCircle />,
      },
    ],
  },
  {
    title: "Más",
    list: [
      {
        title: "Configuración",
        path: "",
        icon: <MdOutlineSettings />,
      },
      {
        title: "Ayuda",
        path: "",
        icon: <MdHelpCenter />,
      },
    ],
  },
];

export const menuCourses = [
  {
    title: "Pages",
    list: [
      {
        title: "Dashboard",
        path: "/courses",
        icon: <MdDashboard />,
      },
      {
        title: "Cursos",
        path: "/courses/curso",
        icon: <MdSupervisedUserCircle />,
      },
      {
        title: "Inscripciones",
        path: "/courses/inscription",
        icon: <MdOutlineContentPaste />,
      },
    ],
  },
  {
    title: "Más",
    list: [
      {
        title: "Configuración",
        path: "",
        icon: <MdOutlineSettings />,
      },
      {
        title: "Ayuda",
        path: "",
        icon: <MdHelpCenter />,
      },
    ],
  },
];

export const bolivianDepartments = [
  "La Paz",
  "Cochabamba",
  "Santa Cruz",
  "Oruro",
  "Potosí",
  "Chuquisaca",
  "Tarija",
  "Beni",
  "Pando",
];

export const departmentData = {
  potosí: {
    provinces: [
      "Alonzo de Ibañez",
      "Quijarro",
      "General Bilbao",
      "Charcas",
      "Chayanta",
      "Cornelio Saavedra",
      "Daniel Campos",
      "Enrique Baldivieso",
      "Linares",
      "Modesto Omiste",
      "Nor Chichas",
      "Nor Lipez",
      "Rafael Bustillo",
      "Sur Chichas",
      "Sur Lipez",
      "Tomas Frias",
    ],
    localities: {
      "modesto omiste": ["Villazón"],
      "alonzo de ibañez": ["Caripuyo", "Sacaca"],
      quijarro: ["Uyuni", "Tomave", "Porco"],
      "general bilbao": ["Arampampa", "Acasio"],
      charcas: ["San Pedro de buena vista", "Toto Toro"],
      chayanta: [
        "Colquechaca",
        "Ravelo",
        "Pocoata",
        "Ocuri",
        "San Pedro de Macha",
      ],
      "cornelio saavedra": ["Betanzos", "Chaqui", "Tacobamba"],
      "daniel campos": ["Llica", "Tahua"],
      "enrique baldivieso": ["San Agustin"],
      linares: ["Puna", "Caiza D", "Ckochas"],
      "nor chichas": ["Santiago de Cotagaita", "Vitichi"],
      "nor lipez": ["Colcha K", "San Pedro de Quemes"],
      "rafael bustillo": ["Uncia", "Chayanta", "Llallagua", "Chuquihuta"],
      "sur chichas": ["Tupiza", "Atocha"],
      "sur lipez": [
        "Mojinete",
        "San Antonio de Esmoruco",
        "San Pablo de Lipez",
      ],
      "tomas frias": ["Potosi", "Tinguipaya", "Yocalla", "Urmiri"],
    },
  },
  "la paz": {
    provinces: [
      "Aroma",
      "Bautista Saavedra",
      "Iturralde",
      "Caranavi",
      "Camacho",
      "Franz Tamayo",
      "Gualberto Villaroel",
      "Ingavi",
      "Inquisivi",
      "General Jose Manuel Pando",
      "Larecaja",
      "Loayza",
      "Los Andes",
      "Manco Kapac",
      "Muñecas",
      "Nor Yungas",
      "Omasuyos",
      "Pacajes",
      "Murillo",
      "Sud Yungas",
    ],
    localities: {
      aroma: [
        "Sica Sica",
        "Umala",
        "Ayo Ayo",
        "Calamarca",
        "Patacamaya",
        "Colquenche",
        "Collana",
      ],
      "bautista saavedra": ["Charazani", "Curva"],
      iturralde: ["Axiamas", "San Buenaventura"],
      caranavi: ["Caranavi", "Alto Beni"],
      camacho: [
        "Puerto Acosta",
        "Mocomoco",
        "Puerto Carabuco",
        "Humanata",
        "Escoma",
      ],
      "franz tamayo": ["Apolo", "Pelechuco"],
      "gualberto villaroel": [
        "San Pedro de Curahuara",
        "Papel Pampa",
        "Chacarilla",
      ],
      ingavi: [
        "Viacha",
        "Guaqui",
        "Tiahuanaco",
        "Desaguadero",
        "San Andres de Machaca",
        "Jesus de Machaca",
        "Taraco",
      ],
      inquisivi: [
        "Inquisivi",
        "Quime",
        "Cajuata",
        "Colquiri",
        "Ichoca",
        "Villa Libertad Licoma",
      ],
      "general jose manuel pando": ["Santiago de Machaca", "Catacora"],
      larecaja: [
        "Sorata",
        "Guanay",
        "Tacacoma",
        "Quiabaya",
        "Combaya",
        "Tipuani",
        "Mapiri",
        "Teoponte",
      ],
      loayza: ["Luribay", "Sapahaqui", "Yaco", "Malla", "Cairoma"],
      "los andes": ["Pucarani", "Laja", "Batallas", "Puerto Perez"],
      "manco kapac": ["Copacabana", "San Pedro de Tiquina", "Tito Yupanqui"],
      muñecas: ["Chuma", "Ayata", "Aucapata"],
      "nor yungas": ["Coroico", "Coripata"],
      omasuyos: [
        "Achacachi",
        "Ancoraimes",
        "Chua Cocani",
        "Huarina",
        "Santiago de Huata",
        "Huatajata",
      ],
      pacajes: [
        "Coro Coro",
        "Caquiaviri",
        "Calacoto",
        "Comanche",
        "Charaña",
        "Waldo Ballivian",
        "Nazacra de Pacajes",
        "Callapa",
      ],
      murillo: ["La Paz", "El Alto", "Mecapaca", "Achocalla", "Palca"],
      "sud yungas": [
        "Chulumani",
        "Irupana",
        "Yanacachi",
        "Palos Blancos",
        "La Asunta",
      ],
    },
  },
  cochabamba: {
    provinces: [
      "Arani",
      "Esteban Arze",
      "Arque",
      "Ayopaya",
      "Campero",
      "Capinota",
      "Cercado",
      "Carrasco",
      "Chapare",
      "German Jordan",
      "Mizque",
      "Punata",
      "Quillacollo",
      "Tapacari",
      "Bolivar",
      "Tiraque",
    ],
    localities: {
      arani: ["Arani", "Vacas"],
      "esteban arze": ["Tarata", "Anzaldo", "Arbieto", "Sacabamba"],
      arque: ["Arque", "Tacopaya"],
      ayopaya: ["Independencia", "Morochata", "Cocapata"],
      campero: ["Aiquile", "Pasorapa", "Omereque"],
      capinota: ["Villa Capinota", "Sativañez", "Sicaya"],
      cercado: ["Cochabamba"],
      carrasco: [
        "Totora",
        "Pojo",
        "Pocona",
        "Chimore",
        "Puerto Villarroel",
        "Entre Rios",
      ],
      chapare: ["Sacaba", "Colomi", "Villa Tunari"],
      "german jordan": ["Cliza", "Toco", "Tolata"],
      mizque: ["Mizque", "Vila Vila", "Alalay"],
      punata: ["Punata", "Villa Rivero", "San Benito", "Tacachi", "Cuchumuela"],
      quillacollo: [
        "Quillacollo",
        "Sipe Sipe",
        "Tiquipaya",
        "Vinto",
        "Colcapirhua",
      ],
      tapacari: ["Tapacari"],
      bolivar: ["Bolivar"],
      tiraque: ["Tiraque", "Shinahota"],
    },
  },
  "santa cruz": {
    provinces: [
      "Andres Ibañez",
      "Angel Sandoval",
      "Caballero",
      "Chiquitos",
      "Cordillera",
      "Florida",
      "German Busch",
      "Guarayos",
      "Ichilo",
      "Ñuflo de Chaves",
      "Obispo Santistevan",
      "Sara",
      "Vallegrande",
      "Velasco",
      "Warnes",
    ],
    localities: {
      "andres ibañez": [
        "Santa Cruz de la Sierra",
        "Cotoca",
        "Porongo",
        "La Guardia",
        "El Torno",
      ],
      "angel sandoval": ["San Matias"],
      caballero: ["Comarapa", "Saipina"],
      chiquitos: ["San Jose de Chiquitos", "Pailon", "Robore"],
      cordillera: [
        "Lagunillas",
        "Charagua",
        "Cabezas",
        "Cuevo",
        "Gutierrez",
        "Camiri",
        "Boyuibe",
      ],
      florida: ["Samaipata", "Pampagrande", "Mairana", "Quirusillas"],
      "german busch": [
        "Puerto Suarez",
        "Puerto Quijarro",
        "El Carmen Rivero Torrez",
      ],
      guarayos: ["Ascension de Guarayos", "Urubicha", "El Puente"],
      ichilo: ["Buena Vista", "San Carlos", "Yapacani", "San Juan de Yapacani"],
      "ñuflo de chaves": [
        "Concepcion",
        "San Javier",
        "San Julian",
        "San Ramon",
        "Cuatro Cañadas",
        "San Antonio de Lomerio",
      ],
      "obispo santistevan": [
        "Montero",
        "Mineros",
        "General Saavedra",
        "Fernandez Alonso",
        "San Pedro",
      ],
      sara: ["Portachuelo", "Santa Rosa del Sara", "Colpa Belgica"],
      vallegrande: [
        "Pucara",
        "Moro Moro",
        "Postrer Valle",
        "Trigal",
        "Vallegrande",
      ],
      velasco: [
        "San Ignacio de Velasco",
        "San Miguel de Velasco",
        "San Rafael de Velasco",
      ],
      warnes: ["Warnes", "Okinawa"],
    },
  },
  oruro: {
    provinces: [
      "Tomas Barron",
      "Cercado",
      "Dalence",
      "Poopo",
      "Abaroa",
      "Sebastian Pagador",
      "Saucari",
      "Nor Carangas",
      "San Pedro de Totora",
      "Carangas",
      "Sud Carangas",
      "Ladislao Cabrera",
      "Litoral",
      "Sajama",
      "Sabaya",
      "Mejillones",
    ],
    localities: {
      "tomas barron": ["Eucaliptus"],
      cercado: ["Oruro", "Caracollo", "El Choro", "Paria"],
      dalence: ["Huanuni", "Machacamarca"],
      poopo: ["Poopo", "Pazña", "Antequera"],
      abaroa: ["Challapata", "Quillacas"],
      "sebastian pagador": ["Santiago de Huari"],
      saucari: ["Toledo"],
      "nor carangas": ["Huayllamarca"],
      "san pedro de totora": ["San Pedro de Totora"],
      carangas: ["Corque", "Choquecota"],
      "sud carangas": ["Santiago de Andamarca", "Belen de Andamarca"],
      "ladislao cabrera": ["Salinas de Garci Mendoza", "Pampa Aullagas"],
      litoral: [
        "Huachacalla",
        "Escara",
        "Cruz de Machacamarca",
        "Yunguyo de Litoral",
        "Esmeralda",
      ],
      sajama: ["Curahuara de Carangas", "Turco"],
      sabaya: ["Sabaya", "Coipasa", "Chipaya"],
      mejillones: ["La Rivera", "Todos Santos", "Carangas"],
    },
  },
  chuquisaca: {
    provinces: [
      "Azurduy",
      "Belisario Boeto",
      "Hernando Siles",
      "Luis Calvo",
      "Nor Cinti",
      "Oropeza",
      "Sud Cinti",
      "Tomina",
      "Yamparaez",
      "Zudañez",
    ],
    localities: {
      azurduy: ["Azurduy", "Tarvita"],
      "belisario boeto": ["Villa Serrano"],
      "hernando siles": ["Monteagudo", "Huacareta"],
      "luis calvo": ["Muyupampa", "Huacaya", "Machareti"],
      "nor cinti": ["Camargo", "San Lucas", "Incahuasi", "Villa Charcas"],
      oropeza: ["Sucre", "Yotala", "Poroma"],
      "sud cinti": ["Villa Abecia", "Culpina", "Las Carreras"],
      tomina: ["Padilla", "Tomina", "Sopachuy", "Villa Alcala", "EL Villar"],
      yamparaez: ["Tarabuco", "Yamparaez"],
      zudañez: ["Zudañez", "Presto", "Mojocoya", "Icla"],
    },
  },
  tarija: {
    provinces: [
      "Oconnor",
      "Cercado",
      "Jose Maria Aviles",
      "Mendez",
      "Gran Chaco",
      "Arce",
    ],
    localities: {
      oconnor: ["San Luis de Entre Rios"],
      cercado: ["Tarija"],
      "jose maria aviles": ["Uriondo", "Yunchara"],
      mendez: ["El Puente", "San Lorenzo"],
      "gran chaco": ["Yacuiba", "Carapari", "Villa Montes"],
      arce: ["Padcaya", "Bermejo"],
    },
  },
  beni: {
    provinces: [
      "Cercado",
      "Antonio Vaca Diez",
      "General Jose Ballivian",
      "Yacuma",
      "Mojos",
      "Marban",
      "Mamore",
      "Itenez",
    ],
    localities: {
      cercado: ["Trinidad", "San Javier"],
      "antonio vaca diez": ["Riberalta", "Guayaramerin"],
      "general jose ballivian": [
        "Santos Reyes",
        "San Borja",
        "Santa Rosa",
        "Rurrenabaque",
      ],
      yacuma: ["Santa Ana de Yucuma", "Exaltacion"],
      mojos: ["San Ignacio de Moxos"],
      marban: ["Nuestra Señora de Loreto", "San Andres"],
      mamore: ["San Joaquin", "San Ramon", "Puerto Siles"],
      itenez: ["Nuestra Señora de Magdalena", "Baures", "Huacaraje"],
    },
  },
  pando: {
    provinces: [
      "Abuna",
      "Federico Roman",
      "Madre de Dios",
      "Manuripi",
      "Nicolas Suarez",
    ],
    localities: {
      abuna: ["Santa Rosa de Abuna", "Ingavi"],
      "federico roman": ["Nueva Esperanza", "Villa Nueva", "Santos Mercado"],
      "madre de dios": ["Puerto Gonzalo Moreno", "San Lorenzo", "Sena"],
      manuripi: ["Puerto Rico", "San Pedro", "Filadelfia"],
      "nicolas suarez": ["Cobija", "Porvenir", "Bolpebra", "Bella Flor"],
    },
  },
};
